language: go

go:
  - 1.12.x
  - 1.11.x
  - tip

env: GO111MODULE=on

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

jobs:
  include:
    stage: build_test
      name: 'Install dependencies, test and build golang packages'
      before_install:
        - go mod download
      install:
        - go get github.com/haya14busa/goverage
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
      before_script:
        - PKGS=$(go list ./...)
      script:
        - diff -u <(echo -n) <(gofmt -d ./)                                    # Fail if a .go file hasn't been formatted with gofmt
        - goverage -v -race -covermode=atomic -coverprofile=coverage.txt $PKGS # Run all tests with coverage
        - go vet -v ./...                                                      # static analyisis
        - golangci-lint run ./...
    stage: deploy
      name: 'Deploy via Serverless to GCP'
      node_js: 12
      script:
        - npm install -g serverless
        - sls deploy


