language: go

go:
  - 1.12.x
  - tip

env: GO111MODULE=on

before_install:
  - openssl aes-256-cbc -K $encrypted_89b033158cc6_key -iv $encrypted_89b033158cc6_iv -in gcloud_raspy.json.enc -out ~/gcloud_raspy.json -d
  - go mod download

install:
  - go get github.com/haya14busa/goverage
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
  - npm install -g serverless
  - npm install --save serverless-google-cloudfunctions

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false

before_script:
  - PKGS=$(go list ./...)

script:
  - diff -u <(echo -n) <(gofmt -d ./)                                    # Fail if a .go file hasn't been formatted with gofmt
  - goverage -v -race -covermode=atomic -coverprofile=coverage.txt $PKGS # Run all tests with coverage
  - go vet -v ./...                                                      # static analyisis
  - golangci-lint run ./...
  - sls deploy

after_success:
  - bash <(curl -s https://codecov.io/bash)
