service: simplex

provider:
  name: google
  runtime: go111
  project: raspy-276913
  credentials: ~/gcloud_raspy.json
  prependService: true
  prependStage: true
  region: asia-northeast1

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  hello:
    handler: Hello
    unauthenticatedAccess: true
    events:
      - http: hello
