// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Image struct {
	Src string  `json:"src"`
	Alt *string `json:"alt"`
}

type Link struct {
	Src  string `json:"src"`
	Text string `json:"text"`
}

type Page struct {
	ID     string   `json:"id"`
	Src    string   `json:"src"`
	Links  []*Link  `json:"links"`
	Images []*Image `json:"images"`
	Videos []*Video `json:"videos"`
}

type Video struct {
	Src       string `json:"src"`
	Thumbnail *Image `json:"thumbnail"`
}
